stages:
- name: publish
  steps:
  - publishImageConfig:
      shellScript: cp -r hub.tansun.com /etc/docker/certs.d
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: hello-world:${CICD_EXECUTION_SEQUENCE}
      env:
        PLUGIN_DEBUG: "true" 
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 120
branch:
  include:
  - master
