stages:
- name: cp-certs
  steps:
  - runScriptConfig:
      image: hub.tansun.com/test/maven:3.6
      shellScript: 'cp -r hub.tansun.com /etc/docker/certs.d/hub.tansun.com'
- name: publish
  steps:
  - publishImageConfig:
      shellScript: cp -r hub.tansun.com /etc/docker/certs.d/hub.tansun.com
      dockerfilePath: -v /etc/docker/certs.d/:/etc/docker/certs.d/ ./Dockerfile
      buildContext: .
      tag: hello-world:${CICD_EXECUTION_SEQUENCE}
      env:
        PLUGIN_DEBUG: "true" 
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 120
branch:
  include:
  - master
