stages:
- name: cp-certs
  steps:
  - runScriptConfig:
      image: hub.tansun.com/test/maven:3.6
      shellScript: 'cp -r hub.tansun.com /etc/docker/certs.d/hub.tansun.com && docker  login -u admin -p Harbor12345  hub.tansun.com && docker  tag hello-world:1.0-SNAPSHOT  hub.tansun.com/test/hello-world:1.0-SNAPSHOT && docker  push hub.tansun.com/test/hello-world:1.0-SNAPSHOT'
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 120
branch:
  include:
  - master
