stages:
- name: compile
  steps:
  - runScriptConfig:
      image: hub.tansun.com/test/tjmas-maven:3.6
      shellScript: mvn clean package
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: test/hello-world:1.0
      pushRemote: true
      registry: hub.tansun.com
  env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
  env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
timeout: 120
branch: {}
