stages:
- name: compile
  steps:
  - runScriptConfig:
      image: hub.tansun.com/test/maven:3.6
      shellScript: mvn -X clean package
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: hello-world:${CICD_EXECUTION_SEQUENCE}
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 120
branch:
  include:
  - master
