stages:
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: hello-world:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: hub.tansun.com
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 120
branch:
  include:
  - master
