stages:
- name: compile
  steps:
  - runScriptConfig:
      image: hub.tansun.com/test/maven:3.6
      shellScript: mvn clean package
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: test/hello-world:1.0
      pushRemote: true
      registry: hub.tansun.com
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 120
branch: {}
