stages:
- name: publish
  steps:
  - publishImageConfig:
      args: '-v /etc/docker/certs.d/hub.tansun.com/:/etc/docker/certs.d/hub.tansun.com/'
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: hello-world:${CICD_EXECUTION_SEQUENCE}
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 120
branch:
  include:
  - master
