kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hello-server
  name: hello-server
  namespace: dev
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: hello-server
    spec:
      containers:
       - image: sc-demo/hello-world:1.0.0
         imagePullPolicy: IfNotPresent
         name: hello-server
         resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "200m"
         ports:
         - containerPort: 20000
           name: web
      restartPolicy: Always
status: {}