apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-server
    my-app: myservicemonitor
  namespace: dev
  name: hello-server
spec:
  ports:
  - name: web
    port: 31000
    protocol: TCP
    targetPort: 20000
    nodePort: 31000
  selector:
    app: hello-server
  type: NodePort
status:
  loadBalancer: {}